version: '3.0'

services:

  # =====================
  # Mongo -- data backend
  # =====================
  mongo:
    image: mongo:3.4
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    restart: always
    volumes:
      - /unifi/db:/data/db

  # =====================================
  # Packaged controller `.deb` from Unifi
  # =====================================
  controller:
    image: "jacobalberty/unifi:5.12.66-arm32v7"
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    depends_on:
      - mongo
    restart: always
    volumes:
      - /unifi/data:/unifi/data
      - /unifi/log:/unifi/log
      - /unifi/cert:/unifi/cert
      - /unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

  logs:
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - /unifi/log:/unifi/log
